---
- hosts: localhost
  tasks:
    - name: Install npm
      package:
        name: npm
        state: present
    - name: Creates directory
      file:
        path: /home/app
        state: directory
    - name: unarchive the code
      unarchive:
        src: /home/app.tar.gz
        dest: /home
    - name: run the startup script
      shell: cat {{ /tmp/startup.sh|quote }}

